import turtle
square = turtle.Turtle()
#bg
turtle.bgcolor("navy")

#outer
square.color("orange")
square.begin_fill()
square.forward(500)
square.left(90) 
square.forward(250)
square.left(90) 
square.forward(500)#up
square.left(90) 
square.forward(250)#side
square.left(90)
square.forward(500)
square.end_fill()

#innner
square.color("green")
square.left(90)
square.forward(83.3)
square.left(90)
square.forward(500)
square.right(90)
square.forward(83.3)
square.right(90)
square.forward(500)
square.backward(500)
square.right(90)
square.forward(83.3)
square.left(90)
square.forward(250)
square.end_fill()
square.color("blue")
for i in range(1):
    square.circle(42.5)
    square.left(90)
    square.forward(85)
    square.backward(42.5)
    square.left(90)
    square.forward(42.5)
    square.backward(85)
    square.forward(42.5)
    square.left(45)
    square.forward(42.5)
    square.backward(85)
    square.forward(42.5)
    square.left(90)
    square.forward(42.5)
    square.backward(85)
    square.end_fill()
turtle.done()
